FROM {{ item.image }}

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        systemd systemd-sysv \
        sudo \
        python3 \
        dbus \
        ca-certificates \
        curl \
        tzdata \
        procps \
        iproute2 \
        gettext-base && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -f /lib/systemd/system/multi-user.target.wants/* \
          /etc/systemd/system/*.wants/* \
          /lib/systemd/system/local-fs.target.wants/* \
          /lib/systemd/system/sockets.target.wants/*udev* \
          /lib/systemd/system/sockets.target.wants/*initctl* \
          /lib/systemd/system/sysinit.target.wants/systemd-tmpfiles-setup* \
          /lib/systemd/system/systemd-update-utmp*

CMD ["/lib/systemd/systemd"]
